server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 2be21de1-bd5b-4b36-9cc4-b048f2956b60
management:
  endpoints:
    web:
      exposure:
        include: '*'
